[build]
  publish = "."
  command = "echo 'Static files ready'"

[dev]
  command = "php -S localhost:8888"
  port = 8888
  publish = "."

[[redirects]]
  from = "/send-mail.php"
  to = "/.netlify/functions/send-mail"
  status = 200

[[redirects]]
  from = "/approve.php"
  to = "/.netlify/functions/approve"
  status = 200

[[redirects]]
  from = "/form-handler.php"
  to = "/.netlify/functions/form-handler"
  status = 200
